// // main1.cpp
// // Duel Tanks - Layer 1 test: Graphics
// // Flash this to verify every GFX function works before moving to Layer 2
// // Each test runs for ~2 seconds then advances automatically
// // ECE319H Spring 2026

// #include "Graphics.h"
// #include "msp.h"

// // ----------------------------------------------------------------
// // Simple busy-wait delay — replace with your SysTick if preferred
// // ----------------------------------------------------------------
// static void Delay_ms(uint32_t ms) {
//     // MSPM0G3507 at 80 MHz: ~80000 cycles per ms
//     for (uint32_t i = 0; i < ms; i++) {
//         for (volatile uint32_t j = 0; j < 8000; j++);
//     }
// }

// // ----------------------------------------------------------------
// // Fake sprite bitmap — 10x10 solid yellow square for testing
// // ----------------------------------------------------------------
// static const uint16_t testBitmap[100] = {
//     0xFFE0,0xFFE0,0xFFE0,0xFFE0,0xFFE0,0xFFE0,0xFFE0,0xFFE0,0xFFE0,0xFFE0,
//     0xFFE0,0xF800,0xF800,0xF800,0xF800,0xF800,0xF800,0xF800,0xF800,0xFFE0,
//     0xFFE0,0xF800,0xFFFF,0xFFFF,0xFFFF,0xFFFF,0xFFFF,0xFFFF,0xF800,0xFFE0,
//     0xFFE0,0xF800,0xFFFF,0xFFFF,0xFFFF,0xFFFF,0xFFFF,0xFFFF,0xF800,0xFFE0,
//     0xFFE0,0xF800,0xFFFF,0xFFFF,0xFFFF,0xFFFF,0xFFFF,0xFFFF,0xF800,0xFFE0,
//     0xFFE0,0xF800,0xFFFF,0xFFFF,0xFFFF,0xFFFF,0xFFFF,0xFFFF,0xF800,0xFFE0,
//     0xFFE0,0xF800,0xFFFF,0xFFFF,0xFFFF,0xFFFF,0xFFFF,0xFFFF,0xF800,0xFFE0,
//     0xFFE0,0xF800,0xFFFF,0xFFFF,0xFFFF,0xFFFF,0xFFFF,0xFFFF,0xF800,0xFFE0,
//     0xFFE0,0xF800,0xF800,0xF800,0xF800,0xF800,0xF800,0xF800,0xF800,0xFFE0,
//     0xFFE0,0xFFE0,0xFFE0,0xFFE0,0xFFE0,0xFFE0,0xFFE0,0xFFE0,0xFFE0,0xFFE0,
// };

// int main(void) {
//     // ---- System init (minimal — expand if your starter needs more) ----
//     SYSCFG_DL_init();   // generated by SysConfig, inits clocks/peripherals
//     GFX_Init();         // LCD init + rotation

//     // ================================================================
//     // TEST 1: Primitives
//     // ================================================================
//     GFX_FillScreen(COLOR_BLACK);
//     GFX_DrawString(2, 2, "TEST 1: PRIMITIVES", COLOR_WHITE, COLOR_BLACK, 1);

//     GFX_FillRect(10,  20, 40, 20, COLOR_RED);
//     GFX_DrawRect(60,  20, 40, 20, COLOR_GREEN);
//     GFX_DrawLine(110, 20, 150, 40, COLOR_BLUE);
//     GFX_DrawCircle(30, 70, 12, COLOR_YELLOW);
//     GFX_FillCircle(80, 70, 10, COLOR_MAGENTA);
//     GFX_DrawLine(0, SCREEN_H-1, SCREEN_W-1, SCREEN_H-1, COLOR_CYAN);

//     Delay_ms(2000);

//     // ================================================================
//     // TEST 2: Text at multiple sizes
//     // ================================================================
//     GFX_FillScreen(COLOR_BLACK);
//     GFX_DrawString(2,  4,  "SIZE 1 TEXT - ABCDEF 0123", COLOR_WHITE,  COLOR_BLACK, 1);
//     GFX_DrawString(2,  20, "SIZE 2",                     COLOR_YELLOW, COLOR_BLACK, 2);
//     GFX_DrawString(2,  40, "SZ3",                        COLOR_CYAN,   COLOR_BLACK, 3);
//     GFX_DrawStringCentered(90, "CENTERED", COLOR_GREEN, COLOR_BLACK, 2);
//     GFX_DrawInt(2, 112, -31415, COLOR_RED, COLOR_BLACK, 1);

//     Delay_ms(2000);

//     // ================================================================
//     // TEST 3: Sprite system — dirty rectangle anti-flicker
//     //         Move sprite across screen, verify no flicker
//     // ================================================================
//     GFX_FillScreen(COLOR_BACKGROUND);
//     GFX_DrawString(2, 2, "TEST 3: SPRITE MOVE", COLOR_WHITE, COLOR_BACKGROUND, 1);

//     Sprite_t testSprite;
//     GFX_SpriteInit(&testSprite, 0, 60, 10, 10, testBitmap);

//     // Move sprite left to right across play area
//     for (int16_t x = 0; x <= SCREEN_W - 10; x += 2) {
//         GFX_SpriteMove(&testSprite, x, 60);
//         GFX_SpriteDraw(&testSprite);
//         Delay_ms(15);
//     }

//     // Move diagonally
//     for (int16_t i = 0; i < 50; i++) {
//         GFX_SpriteMove(&testSprite, SCREEN_W - 10 - i*2, 60 + i);
//         GFX_SpriteDraw(&testSprite);
//         Delay_ms(15);
//     }

//     // Test visibility toggle (cloak)
//     GFX_DrawString(2, 2, "CLOAK TEST: BLINK  ", COLOR_WHITE, COLOR_BACKGROUND, 1);
//     for (uint8_t i = 0; i < 6; i++) {
//         testSprite.visible = !testSprite.visible;
//         testSprite.dirty   = true;
//         GFX_SpriteDraw(&testSprite);
//         Delay_ms(200);
//     }
//     testSprite.visible = true;

//     Delay_ms(500);

//     // ================================================================
//     // TEST 4: HUD
//     // ================================================================
//     GFX_FillScreen(COLOR_BACKGROUND);
//     GFX_DrawHUD(3, 0, 0);
//     GFX_DrawStringCentered(60, "HUD TEST", COLOR_WHITE, COLOR_BACKGROUND, 1);
//     Delay_ms(800);

//     // Simulate taking damage + getting kills + charging ability
//     GFX_UpdateLives(2);     Delay_ms(400);
//     GFX_UpdateLives(1);     Delay_ms(400);
//     GFX_UpdateKills(1);     Delay_ms(300);
//     GFX_UpdateKills(2);     Delay_ms(300);

//     for (uint8_t p = 0; p <= 100; p += 5) {
//         GFX_UpdateCooldownBar(p);
//         Delay_ms(40);
//     }
//     Delay_ms(500);

//     // ================================================================
//     // TEST 5: Explosion animation
//     // ================================================================
//     GFX_FillScreen(COLOR_BACKGROUND);
//     GFX_DrawHUD(3, 0, 0);
//     GFX_DrawString(2, 20, "TEST 5: EXPLOSION", COLOR_WHITE, COLOR_BACKGROUND, 1);

//     int16_t ex = SCREEN_W / 2;
//     int16_t ey = SCREEN_H / 2;

//     for (uint8_t frame = 0; frame < 4; frame++) {
//         GFX_DrawExplosionFrame(ex, ey, frame);
//         Delay_ms(80);
//     }
//     GFX_EraseExplosion(ex, ey);
//     Delay_ms(500);

//     // ================================================================
//     // TEST 6: Incoming warning
//     // ================================================================
//     GFX_FillScreen(COLOR_BACKGROUND);
//     GFX_DrawHUD(3, 0, 0);
//     GFX_DrawString(2, 40, "TEST 6: INCOMING", COLOR_WHITE, COLOR_BACKGROUND, 1);
//     GFX_DrawIncoming();
//     Delay_ms(1500);
//     GFX_ClearIncoming();
//     Delay_ms(500);

//     // ================================================================
//     // TEST 7: Charge bar
//     // ================================================================
//     GFX_FillScreen(COLOR_BACKGROUND);
//     GFX_DrawHUD(3, 0, 0);
//     GFX_DrawString(2, 40, "TEST 7: CHARGE BAR", COLOR_WHITE, COLOR_BACKGROUND, 1);
//     for (uint8_t p = 0; p <= 100; p += 2) {
//         GFX_DrawChargeBar(75, 60, p);
//         Delay_ms(30);
//     }
//     GFX_EraseChargeBar(75, 60);
//     Delay_ms(500);

//     // ================================================================
//     // TEST 8: Screen shake
//     // ================================================================
//     GFX_FillScreen(COLOR_BACKGROUND);
//     GFX_DrawHUD(3, 0, 0);
//     GFX_DrawString(2, 50, "TEST 8: SHAKE", COLOR_WHITE, COLOR_BACKGROUND, 1);
//     GFX_ShakeStart(3);
//     for (uint8_t i = 0; i < 10; i++) {
//         GFX_ShakeTick();
//         // In real game you would shift all sprite draw calls by ShakeOffsetX/Y
//         // Here just visualize the offset values
//         GFX_FillRect(60, 60, 40, 10, COLOR_BACKGROUND);
//         GFX_DrawString(60, 62 + GFX_ShakeOffsetY(), "SHAKING",
//                        COLOR_RED, COLOR_BACKGROUND, 1);
//         Delay_ms(50);
//     }
//     Delay_ms(500);

//     // ================================================================
//     // TEST 9: Full screens
//     // ================================================================

//     // Splash — blink prompt 4 times
//     for (uint8_t i = 0; i < 4; i++) {
//         GFX_DrawSplash(i % 2 == 0);
//         Delay_ms(600);
//     }

//     // Language select — both options highlighted
//     GFX_DrawLanguageSelect(0);  Delay_ms(1000);
//     GFX_DrawLanguageSelect(1);  Delay_ms(1000);

//     // Rules pages
//     GFX_DrawRulesPage(0, 0);    Delay_ms(2000);
//     GFX_DrawRulesPage(1, 0);    Delay_ms(2000);
//     GFX_DrawRulesPage(2, 0);    Delay_ms(2000);

//     // Rules pages in Spanish
//     GFX_DrawRulesPage(0, 1);    Delay_ms(1500);
//     GFX_DrawRulesPage(1, 1);    Delay_ms(1500);
//     GFX_DrawRulesPage(2, 1);    Delay_ms(1500);

//     // Tank select — cycle through tanks
//     GFX_DrawTankSelect(0, -1, false, 0);  Delay_ms(800);
//     GFX_DrawTankSelect(1, -1, false, 0);  Delay_ms(800);
//     GFX_DrawTankSelect(2,  0, false, 0);  Delay_ms(800);  // opponent on tank 0
//     GFX_DrawTankSelect(2,  0, true,  0);  Delay_ms(800);  // opponent ready

//     // Waiting screen
//     for (uint8_t d = 0; d < 12; d++) {
//         GFX_DrawWaiting(d, 0);
//         Delay_ms(300);
//     }

//     // Countdown
//     GFX_DrawCountdown(3);   Delay_ms(800);
//     GFX_DrawCountdown(2);   Delay_ms(800);
//     GFX_DrawCountdown(1);   Delay_ms(800);
//     GFX_DrawCountdown(0);   // FIGHT! includes its own delay

//     // End screens
//     GFX_DrawEndScreen(true,  3, 0);
//     GFX_DrawRematch(0);
//     Delay_ms(2000);

//     GFX_DrawEndScreen(false, 1, 0);
//     GFX_DrawRematch(0);
//     Delay_ms(2000);

//     // Spanish end screen
//     GFX_DrawEndScreen(true, 2, 1);
//     GFX_DrawRematch(1);
//     Delay_ms(2000);

//     // ================================================================
//     // TEST COMPLETE
//     // ================================================================
//     GFX_FillScreen(COLOR_BLACK);
//     GFX_DrawStringCentered(50,  "ALL GFX TESTS", COLOR_GREEN, COLOR_BLACK, 1);
//     GFX_DrawStringCentered(62,  "PASSED",         COLOR_GREEN, COLOR_BLACK, 2);
//     GFX_DrawStringCentered(90,  "Layer 2 next:",  COLOR_WHITE, COLOR_BLACK, 1);
//     GFX_DrawStringCentered(102, "Buttons + ADC",  COLOR_CYAN,  COLOR_BLACK, 1);

//     while (1);  // halt here
// }
